### Importación de datos

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda2.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

In [ ]:

import pandas as pd


#Agregamos una columna que identifique las tiendas
tienda['Tienda'] = 'Tienda 1'
tienda2['Tienda'] = 'Tienda 2'
tienda3['Tienda'] = 'Tienda 3'
tienda4['Tienda'] = 'Tienda 4'


#Concatenamos los DF y generamos uno nuevo
tiendas_consolidado = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

tiendas_consolidado

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon,Tienda
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175,Tienda 1
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359,Tienda 1
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444,Tienda 1
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250,Tienda 1
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359,Tienda 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9430,Mesa de comedor,Muebles,227700.0,12600.0,12/02/2020,Camila Rivera,Medellín,5,Tarjeta de crédito,1,6.25184,-75.56359,Tienda 4
9431,Silla de oficina,Muebles,342000.0,18600.0,17/05/2022,Felipe Santos,Bucaramanga,5,Tarjeta de crédito,3,7.12539,-73.11980,Tienda 4
9432,Vaso térmico,Deportes y diversión,36700.0,2400.0,03/05/2022,Camila Rivera,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4
9433,Set de ollas,Artículos para el hogar,151800.0,8300.0,15/06/2020,Blanca Ramirez,Cali,5,Tarjeta de crédito,1,3.43722,-76.52250,Tienda 4
9434,Cuerda para saltar,Deportes y diversión,11200.0,1300.0,17/11/2021,Felipe Santos,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,Tienda 4

#1. Análisis de facturación

In [ ]:
# Se genera un DF de las ventas por tienda
ventas_por_tienda = tiendas_consolidado.groupby('Tienda')['Precio'].sum().astype(int).apply(lambda x: "${:,.0f}".format(x))

# Display the result
ventas_por_tienda

Tienda
Tienda 1    $1,150,880,400
Tienda 2    $1,116,343,500
Tienda 3    $1,098,019,600
Tienda 4    $1,038,375,700
Name: Precio, dtype: object

# 2. Ventas por categoría

In [ ]:
# Agrupacion de los datos por categoria y tiendas, y se sumariza por los precios
ventas_por_categoria_y_tienda = tiendas_consolidado.groupby(["Categoría del Producto", "Tienda"])["Precio"].sum()

# Procesamiento y formateo de los precios
ventas_por_categoria_y_tienda = ventas_por_categoria_y_tienda.astype(int).apply(lambda x: "${:,.0f}".format(x))

# Visualizacion del resultado
ventas_por_categoria_y_tienda

Categoría del Producto   Tienda
Artículos para el hogar  Tienda 1     $12,698,400
                         Tienda 2     $14,746,900
                         Tienda 3     $15,060,000
                         Tienda 4     $15,074,500
Deportes y diversión     Tienda 1     $39,290,000
                         Tienda 2     $34,744,500
                         Tienda 3     $35,593,100
                         Tienda 4     $33,350,100
Electrodomésticos        Tienda 1    $363,685,200
                         Tienda 2    $348,567,800
                         Tienda 3    $329,237,900
                         Tienda 4    $283,260,200
Electrónicos             Tienda 1    $429,493,500
                         Tienda 2    $410,831,100
                         Tienda 3    $410,775,800
                         Tienda 4    $409,476,100
Instrumentos musicales   Tienda 1     $91,299,000
                         Tienda 2    $104,990,300
                         Tienda 3     $77,380,900
                         Tienda 4     $75,102,400
Juguetes                 Tienda 1     $17,995,700
                         Tienda 2     $15,945,400
                         Tienda 3     $19,401,100
                         Tienda 4     $20,262,200
Libros                   Tienda 1      $8,784,900
                         Tienda 2     $10,091,200
                         Tienda 3      $9,498,700
                         Tienda 4      $9,321,300
Muebles                  Tienda 1    $187,633,700
                         Tienda 2    $176,426,300
                         Tienda 3    $201,072,100
                         Tienda 4    $192,528,900
Name: Precio, dtype: object

# 3. Calificación promedio de la tienda

In [ ]:

# Se agrupa por Tienda y calcula el promedio de la calificacion
average_classification_by_store = tiendas_consolidado.groupby('Tienda')['Calificación'].mean()

# Visualizacion del resultado
average_classification_by_store

Tienda
Tienda 1    3.976685
Tienda 2    4.037304
Tienda 3    4.048326
Tienda 4    3.995759
Name: Calificación, dtype: float64

# 4. Productos más y menos vendidos

In [ ]:

# Se Agrupan los datos por tienda y producto, luego se cuentan  cada producto
product_counts = tiendas_consolidado.groupby(['Tienda', 'Producto'])['Producto'].count().reset_index(name='counts')

# Funcion que encuentra los productos mas y menos vendidos
def find_extremes(x):
    # Ordenar  y obtener el primero (máximo) y el último (mínimo)
    sorted_products = x.sort_values('counts')
    return pd.DataFrame({
        'Tienda': [x.iloc[0]['Tienda']] * 2,
        'Producto': [sorted_products.iloc[-1]['Producto'], sorted_products.iloc[0]['Producto']],
        'Type': ['Mas vendido', 'Menos vendido'],
        'Counts': [sorted_products.iloc[-1]['counts'], sorted_products.iloc[0]['counts']]
    })

# Aplicar la funcion para cada año
extremes_df = product_counts.groupby('Tienda').apply(find_extremes).reset_index(drop=True)

# Visualizacion del resultado
extremes_df

<ipython-input-6-5544a8cf33a6>:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  extremes_df = product_counts.groupby('Tienda').apply(find_extremes).reset_index(drop=True)

     Tienda                   Producto           Type  Counts
0  Tienda 1              TV LED UHD 4K    Mas vendido      60
1  Tienda 1  Auriculares con micrófono  Menos vendido      33
2  Tienda 2  Iniciando en programación    Mas vendido      65
3  Tienda 2              Juego de mesa  Menos vendido      32
4  Tienda 3              Kit de bancas    Mas vendido      57
5  Tienda 3    Bloques de construcción  Menos vendido      35
6  Tienda 4                   Cama box    Mas vendido      62
7  Tienda 4         Guitarra eléctrica  Menos vendido      33

# 5. Envío promedio por tienda

In [ ]:
# Determinacion del costo de envio promedio por tienda
average_costo_envio_by_store = tiendas_consolidado.groupby('Tienda')['Costo de envío'].mean().apply(lambda x: "${:,.0f}".format(x))

# Visualizacion del resultado
average_costo_envio_by_store

Tienda
Tienda 1    $26,019
Tienda 2    $25,216
Tienda 3    $24,806
Tienda 4    $23,459
Name: Costo de envío, dtype: object